// Time
export const START_SIMULATION = 'START_SIMULATION'
export const PAUSE_SIMULATION = 'PAUSE_SIMULATION'
export const TOGGLE_MENU_VISIBILITY = 'TOGGLE_MENU_VISIBILITY'

// Finance
export const DAILY_FINANCIAL_UPDATE = 'DAILY_FINANCIAL_UPDATE'

// HR
export const HIRE_EMPLOYEE = 'HIRE_EMPLOYEE'
export const FIRE_EMPLOYEE = 'FIRE_EMPLOYEE'
export const TRAIN_EMPLOYEE = 'TRAIN_EMPLOYEE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SET_WORKING_TIME_MODEL = 'SET_WORKING_TIME_MODEL'

// Production
export const SWITCH_CURRENT_COMPONENT = 'SWITCH_CURRENT_COMPONENT'

// Marketing
export const START_CAMPAIGN = 'START_CAMPAIGN'
export const MAKE_PRESS_RELEASE = 'MAKE_PRESS_RELEASE'
export const DO_MARKET_RESEARCHES = 'DO_MARKET_RESEARCHES'
export const HIRE_CONSULTANCY = 'HIRE_CONSULTANCY'
export const HIRE_LOBBYIST = 'HIRE_LOBBYIST'
