// Time
export const START_SIMULATION = 'START_SIMULATION'
export const PAUSE_SIMULATION = 'PAUSE_SIMULATION'
export const TOGGLE_MENU_VISIBILITY = 'TOGGLE_MENU_VISIBILITY'

// Finance
export const DAILY_FINANCIAL_UPDATE = 'DAILY_FINANCIAL_UPDATE'

// HR
export const MONTHLY_HR_HISTORY_UPDATE = 'MONTHLY_HR_HISTORY_UPDATE'

export const HIRE_EMPLOYEE = 'HIRE_EMPLOYEE'
export const FIRE_EMPLOYEE = 'FIRE_EMPLOYEE'
export const TRAIN_EMPLOYEE = 'TRAIN_EMPLOYEE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SET_WORKING_TIME_MODEL = 'SET_WORKING_TIME_MODEL'
export const SET_WORKING_HOURS = 'SET_WORKING_HOURS'
export const SET_COMPANY_CAR = 'SET_COMPANY_CAR'
export const SET_FOOD_BENEFITS = 'SET_FOOD_BENEFITS'
export const SET_GYM_BENEFITS = 'SET_GYM_BENEFITS'

// Production
export const INTRODUCE_NEW_PRODUCT = 'INTRODUCE_NEW_PRODUCT'
export const DEPRECATE_PRODUCT = 'DEPRECATE_PRODUCT'
export const SWITCH_CURRENT_COMPONENT = 'SWITCH_CURRENT_COMPONENT'
export const BUY_MACHINE = 'BUY_MACHINE'
export const SELL_MACHINE = 'SELL_MACHINE'
export const BUY_TRUCK = 'BUY_TRUCK'
export const SELL_TRUCK = 'SELL_TRUCK'

export const SWITCH_LOGISTIC_PARTNER = 'SWITCH_LOGISTIC_PARTNER'

// Marketing
export const START_CAMPAIGN = 'START_CAMPAIGN'
export const MAKE_PRESS_RELEASE = 'MAKE_PRESS_RELEASE'
export const DO_MARKET_RESEARCHES = 'DO_MARKET_RESEARCHES'
export const HIRE_CONSULTANCY = 'HIRE_CONSULTANCY'
export const HIRE_LOBBYIST = 'HIRE_LOBBYIST'
