// Time
export const START_SIMULATION = 'START_SIMULATION'
export const PAUSE_SIMULATION = 'PAUSE_SIMULATION'

// Finance
export const MAKE_REVENUE = 'MAKE_REVENUE'
export const PAY_COSTS = 'PAY_COSTS'

// HR
export const HIRE_EMPLOYEE = 'HIRE_EMPLOYEE'
export const FIRE_EMPLOYEE = 'FIRE_EMPLOYEE'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

// Production
export const SWITCH_CURRENT_COMPONENT = 'SWITCH_CURRENT_COMPONENT'
